config/routes.rb
Rails.application.routes.draw do
  root to: 'game#home'
  get 'mode',to: 'game#mode'
  get 'explanation',to: 'game#explanation'
  get 'setting',to: 'game#setting'
  get 'play',to: 'game#play'
  get 'nomal_easy', to: 'game#nomal_easy'
  get 'nomal_medium', to: 'game#nomal_medium'
  get 'nomal_hard', to: 'game#nomal_hard'
  get 'rank_easy', to: 'game#rank_easy'
  get 'rank_medium', to: 'game#rank_medium'
  get 'rank_hard', to: 'game#rank_hard'
  get 'result', to: 'game#result'

  resources :scores, only: [:index, :new, :create]
  get 'level_1', to: 'scores#level_1'
  get 'level_2', to: 'scores#level_2'
  get 'level_3', to: 'scores#level_3'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/score.rb
class Score < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def play
  end

  def home
  end

  def encode_ja(url)
    ret = ""
    url.split(//).each do |c|
      if  /[-_.!~*'()a-zA-Z0-9;\/\?:@&=+$,%#]/ =~ c
        ret.concat(c)
      else
        ret.concat(CGI.escape(c))
      end
    end
    return ret
  end

  def explanation
  end

  def setting
  end

  def mode
  end

  def nomal_easy
  end

  def nomal_medium
  end

  def nomal_hard
  end

  def rank_easy
  end

  def rank_medium
  end

  def rank_hard
  end

  def result
    @result = params[:score]
    @level = params[:level]
    @score = Score.new
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def level_1
    @sort = Score.where(level: 1)
    @score = @sort.order(score: :desc)
    @number = 1
  end
  
  def level_2
    @sort = Score.where(level: 2)
    @score = @sort.order(score: :desc)
    @number = 1
  end

  def level_3
    @sort = Score.where(level: 3)
    @score = @sort.order(score: :desc)
    @number = 1
  end

  def index
    @sort1 = Score.where(level: 1)
    @score1 = @sort1.order(score: :desc)
    @sort2 = Score.where(level: 2)
    @score2 = @sort2.order(score: :desc)
    @sort3 = Score.where(level: 3)
    @score3 = @sort3.order(score: :desc)
    @number = 1
  end
  
  def new
  end

  def create
    @score = Score.new(score_params)
    if @score.name.present?
      @score.save!
      if @score.level == 1
        redirect_to level_1_path
      elsif @score.level == 2
        redirect_to level_2_path
      elsif @score.level == 3
        redirect_to level_3_path
      end
    else
      flash[:alert] = "名前を入力してください"
      redirect_to request.referer
    end
  end

private
  def score_params
    params.require(:score).permit(:name,:score,:level)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/score_helper.rb
module ScoreHelper
end

app/views/game/explanation.html.erb
<div class="explanation_box">
  <center>
    <div class="point_box">
      <span class="point-title">ルール</span>
      <p>制限時間内にハンター文字を読んでタイピング！
      <%=link_to("https://half-a.net/sozai-page4") do %>
        <button class="explanation_btn btn-secondary btn-lg" >ハンター文字お借りしました(外部サイトが開きます)</button>
      <%end%>
      </p>
    </div>
    <div class="point_box">
      <span class="point-title">ノーマルモード</span>
      <p>ふりがな/ローマ字表示でハンター文字を覚えながら</br>タイピング練習をしよう！</p>
    </div>
    <div class="point_box">
      <span class="point-title">ランキングモード</span>
      <p>ハンター文字のみのモード！</br>ランキング上位を目指してハイスコアを記録しよう！</p>
    </div>
    <div class="point_box">
      <span class="point-title">連打ボーナス</span>
      <p>正しい入力を続ければメーターが貯まり</br>一定数続けられると残り秒数が増える！</p>
    </div>
    <%=link_to(root_path) do %>
      <button class="explanation_btn" >タイトルに戻る</button>
    <%end%>
  </center>
</div>

app/views/game/home.html.erb
<div class="box">
	<center>
		<h1 class = "logo_font">ハンター打</h1>
		<%= link_to("プレイ", mode_path, {class: "btn-circle-flat"}) %>
		</br>
		<%= link_to("遊び方", explanation_path, {class: "reset flat border"}) %>
		<%= link_to("設定", setting_path, {class: "reset flat border"}) %>
		<%= link_to "http://twitter.com/share?url=#{"https://translate.google.com/?hl=ja&tab=TT"}/&text=ハンター打でハンター文字を覚えよう！&hashtags=ハンター打", target: '_blank' do %>
			<i class="fa-brands fa-twitter sns_size" style='color: #3399FF;'></i>
		<% end %>
		<div class="line-it-button" data-lang="ja" data-type="share-b" data-env="REAL" data-url="https://translate.google.com/?hl=ja&tab=TT" data-color="default" data-size="small" data-count="false" data-ver="3" style="display: none;"></div>
			<script src="https://www.line-website.com/social-plugins/js/thirdparty/loader.min.js" async="async" defer="defer"></script>
		</div>
	</center>
</div>
# <% uri = URI.encode_www_form_component("http://twitter.com/share?url=#{"https://translate.google.com/?hl=ja&tab=TT"}/&text=ハンター打でハンター文字を覚えよう！&hashtags=ハンター打") %>

app/views/game/mode.html.erb
<div class="mode_box">
<h1 class = "mode_title">モード選択</h1>
  <ul class="list list--1">
    <ul class="list__list">
      <li class="mode_name">ノーマルモード</li>
      <li>
        <%=link_to(nomal_easy_path) do %>
          <button class="reset flat border" >EASY</button>
        <%end%>
      </li>
      <li>
        <%=link_to(nomal_medium_path) do %>
          <button class="reset flat border" >NOMAL</button>
        <%end%>
      </li>
      <li>
        <%=link_to(nomal_hard_path) do %>
          <button class="reset flat border" >HARD</button>
        <%end%>
      </li>
    </ul>
    <ul class="list__list">
      <li class="mode_name">ランキングモード</li>
      <li>
        <%=link_to(rank_easy_path, class: "rank_easy") do %>
          <button class="reset flat border" >EASY</button>
        <%end%>
      </li>
      <li>
        <%=link_to(rank_medium_path, class: "rank_medium") do %>
          <button class="reset flat border" >NOMAL</button>
        <%end%>
      </li>
      <li>
        <%=link_to(rank_hard_path, class: "rank_hard") do %>
          <button class="reset flat border" >HARD</button>
        <%end%>
      </li>
    </ul>
  </ul>

    <%=link_to(setting_path) do %>
      <button class="reset flat border left" >設定</button>
    <%end%>
    <%=link_to(root_path) do %>
      <button class="reset flat border left" >ホームに戻る</button>
    <%end%>
</div>

app/views/game/nomal_easy.html.erb
<script>
  var level = 0;
</script>
<%= javascript_include_tag "nomal_play.js" %>
<div class="mode_box">
  <center>
    <div class="game_info">
      <h1 class="mode_title">練習モード:easy</h1>
      <h1 class="time">残り時間<output></output>秒</h1>
    </div>
    <div class="game_box">
      <h2 class="kana_q" id="kana">にほんご</h2>
      <h1 class="hunter hunt_q">はんたーもじ</p>
      <h1 class = "rome_q" id="rome" >スペースを押して始める</h1>
      <h1 class="game_score">score: <span id= "totalScore">0</span></h1>
      <div class="prog-bar">
        <progress class ="pg_bar" id="bar" max="6" min="0" value="0" onkeydown=get_prog()></progress>
      </div>
    </div>
    <input type="button" value="日本語表示" onclick="janSwitching()">
    <input type="button" value="ローマ字表示" onclick="romeSwitching()">
    <%=link_to(setting_path) do %>
      <button class="btn btn-secondary btn-lg" >設定</button>
    <%end%>
    <%=link_to(root_path) do %>
      <button class="btn btn-secondary btn-lg" >タイトルに戻る</button>
    <%end%>
  </center>
</div>

app/views/game/nomal_hard.html.erb
<script>
  var level = 0;
</script>
<%= javascript_include_tag "nomal_play.js" %>
<div class="mode_box">
  <center>
    <div class="game_info">
      <h1 class="mode_title">練習モード:hard</h1>
      <h1 class="time">残り時間<output></output>秒</h1>
    </div>
    <div class="game_box">
      <h2 class="kana_q" id="kana">にほんご</h2>
      <h1 class="hunter hunt_q">はんたーもじ</p>
      <h1 class = "rome_q" id="rome" >スペースを押して始める</h1>
      <h1 class="game_score">score: <span id= "totalScore">0</span></h1>
      <div class="prog-bar">
        <progress class ="pg_bar" id="bar" max="6" min="0" value="0" onkeydown=get_prog()></progress>
      </div>
    </div>
    <input type="button" value="日本語表示" onclick="janSwitching()">
    <input type="button" value="ローマ字表示" onclick="romeSwitching()">
    <%=link_to(setting_path) do %>
      <button class="btn btn-secondary btn-lg" >設定</button>
    <%end%>
    <%=link_to(root_path) do %>
      <button class="btn btn-secondary btn-lg" >タイトルに戻る</button>
    <%end%>
  </center>
</div>

app/views/game/nomal_medium.html.erb
<script>
  var level = 0;
</script>
<%= javascript_include_tag "nomal_play.js" %>
<div class="mode_box">
  <center>
    <div class="game_info">
      <h1 class="mode_title">練習モード:nomal</h1>
      <h1 class="time">残り時間<output></output>秒</h1>
    </div>
    <div class="game_box">
      <h2 class="kana_q" id="kana">にほんご</h2>
      <h1 class="hunter hunt_q">はんたーもじ</p>
      <h1 class = "rome_q" id="rome" >スペースを押して始める</h1>
      <h1 class="game_score">score: <span id= "totalScore">0</span></h1>
      <div class="prog-bar">
        <progress class ="pg_bar" id="bar" max="6" min="0" value="0" onkeydown=get_prog()></progress>
      </div>
    </div>
    <input type="button" value="日本語表示" onclick="janSwitching()">
    <input type="button" value="ローマ字表示" onclick="romeSwitching()">
    <%=link_to(setting_path) do %>
      <button class="btn btn-secondary btn-lg" >設定</button>
    <%end%>
    <%=link_to(root_path) do %>
      <button class="btn btn-secondary btn-lg" >タイトルに戻る</button>
    <%end%>
  </center>
</div>

app/views/game/play.html.erb
<html>
	<head>
	<%= javascript_include_tag "play.js" %>
	</head>
	<body>
		<center>
		<h1>残り時間<output></output>秒</h1>
		<h1 id="rome" class="text">何かキーを押して下さい</h1>
		<h2 id="jan" class="text">にほんご</h2>
		<p class="hunter text">はんたーもじ</p>
		<h1>score: <span id= "totalScore">0</span></h1>
		<input type="button" value="日本語表示" onclick="janSwitching()">
		<input type="button" value="ローマ字表示" onclick="romeSwitching()">
		</center>
	</body>
</html>

app/views/game/rank_easy.html.erb
<script>
  var level = 1;
</script>
<%= javascript_include_tag "nomal_play.js" %>
<div class="mode_box">
  <center>
    <div class="game_info">
      <h1 class="mode_title">ランキングモード:easy</h1>
      <h1 class="time">残り時間<output></output>秒</h1>
    </div>
    <div class="game_box">
      <h2 class="kana_q hidden" id="kana">にほんご</h2>
      <h1 class="hunter hunt_q">はんたーもじ</p>
      <h1 class = "rome_q hidden" id="rome" >スペースを押して始める</h1>
      <h1 class="game_score">score: <span id= "totalScore">0</span></h1>
      <div class="prog-bar">
        <progress class ="pg_bar" id="bar" max="6" min="0" value="0" onkeydown=get_prog()></progress>
      </div>
    </div>
    <input type="button" value="日本語表示" onclick="janSwitching()">
    <input type="button" value="ローマ字表示" onclick="romeSwitching()">
    <%=link_to(setting_path) do %>
      <button class="btn btn-secondary btn-lg" >設定</button>
    <%end%>
    <%=link_to(root_path) do %>
      <button class="btn btn-secondary btn-lg" >タイトルに戻る</button>
    <%end%>
  </center>
</div>

app/views/game/rank_hard.html.erb
<script>
  var level = 3;
</script>
<%= javascript_include_tag "nomal_play.js" %>
<div class="mode_box">
  <center>
    <div class="game_info">
      <h1 class="mode_title">ランキングモード:hard</h1>
      <h1 class="time">残り時間<output></output>秒</h1>
    </div>
    <div class="game_box">
      <h2 class="kana_q hidden" id="kana">にほんご</h2>
      <h1 class="hunter hunt_q">はんたーもじ</p>
      <h1 class = "rome_q hidden" id="rome" >スペースを押して始める</h1>
      <h1 class="game_score">score: <span id= "totalScore">0</span></h1>
      <div class="prog-bar">
        <progress class ="pg_bar" id="bar" max="6" min="0" value="0" onkeydown=get_prog()></progress>
      </div>
    </div>
    <input type="button" value="日本語表示" onclick="janSwitching()">
    <input type="button" value="ローマ字表示" onclick="romeSwitching()">
    <%=link_to(setting_path) do %>
      <button class="btn btn-secondary btn-lg" >設定</button>
    <%end%>
    <%=link_to(root_path) do %>
      <button class="btn btn-secondary btn-lg" >タイトルに戻る</button>
    <%end%>
  </center>
</div>

app/views/game/rank_medium.html.erb
<script>
  var level = 2;
</script>
<%= javascript_include_tag "nomal_play.js" %>
<div class="mode_box">
  <center>
    <div class="game_info">
      <h1 class="mode_title">ランキングモード:nomal</h1>
      <h1 class="time">残り時間<output></output>秒</h1>
    </div>
    <div class="game_box">
      <h2 class="kana_q hidden" id="kana">にほんご</h2>
      <h1 class="hunter hunt_q">はんたーもじ</p>
      <h1 class = "rome_q hidden" id="rome" >スペースを押して始める</h1>
      <h1 class="game_score">score: <span id= "totalScore">0</span></h1>
      <div class="prog-bar">
        <progress class ="pg_bar" id="bar" max="6" min="0" value="0" onkeydown=get_prog()></progress>
      </div>
    </div>
    <input type="button" value="日本語表示" onclick="janSwitching()">
    <input type="button" value="ローマ字表示" onclick="romeSwitching()">
    <%=link_to(setting_path) do %>
      <button class="btn btn-secondary btn-lg" >設定</button>
    <%end%>
    <%=link_to(root_path) do %>
      <button class="btn btn-secondary btn-lg" >タイトルに戻る</button>
    <%end%>
  </center>
</div>

app/views/game/result.html.erb
<div id="flash" style="display: none;">
  <% flash.each do |message_type, message| %>
    <%= message %>
  <% end %>
</div>

<div class="result_box">
  <center>
    <%= image_tag 'license_logo.jpg', class: "img license_logo" %>
    <%= image_tag 'barcode.jpg', class: "img" %>
    <div class="score_box">
      <h1 id="score" class="score"><%= @result %>点</h1>
      <p class="hunter">
        はんたーだであそんでくれてどうもありがとう..いまこのぶんしょうがよめているということはもうきみははんたーもじますたーになったということだ..はんたーたちがはっしんしたじょうほうをはんたーもじえすえぬえすでみてみることをおすすめするぞ
      </p>
      <% if @level != "0" %>
        <%= form_for(@score) do |f| %>
          <%= f.text_field :name, placeholder:"ニックネーム", class: "name_field"%>
          <%= f.hidden_field :score, value: @result %>
          <%= f.hidden_field :level, value: @level %>
          <%= f.submit "ランキングに登録", class: "btn btn-primary" %>
          <%= link_to "http://twitter.com/share?url=#{"https://translate.google.com/?hl=ja&tab=TT"}/&text=#{@result}オーラ貸付！ハンター打でハンター文字を覚えよう！&hashtags=ハンター打", target: '_blank' do %>
            <i class="fa-brands fa-twitter sns_size" style='color: #3399FF;'></i>
          <% end %>
        <% end %>
      <% end %>
      <%= link_to :back do %>
        <button class="btn">再挑戦</button>
      <% end %>
      <%=link_to(root_path) do %>
        <button class="btn" >タイトルに戻る</button>
      <%end%>
    </div>
  </center>
</div>

<script>
    var flash_message = document.getElementById("flash").innerHTML.trim();
    if (flash_message){
      alert(flash_message);
    }
</script>

app/views/game/setting.html.erb
<h1>設定</h1>
<%=link_to(root_path) do %>
  <button class="explanation_btn" >タイトルに戻る</button>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ハンター打</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/f882ac6f8a.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <header class="header">
    <h1 class="header-logo">
      <%= link_to("ハンターだ", root_path) %>
    </h1>
    <nav class="header_ul">
        <ul class="header-list">
        <li>
          <%= link_to("ランキング", scores_path, {class: "header-item"}) %>
        </li>
        <li>
          <%= link_to("HunterTwitter", scores_path, {class: "header-item header-item--contact"}) %>
        </li>
        </ul>
    </nav>
  </header>
  <div id="content">
    <body>
      <%= yield %>
    </body>
  </div>
  <footer>
  </footer>
</html>

app/views/scores/create.html.erb
<h1>Score#create</h1>
<p>Find me in app/views/scores/create.html.erb</p>

app/views/scores/index.html.erb
<!DOCTYPE html>
<html lang="jp">
<head>
  <meta charset="UTF-8">
  <title>Tab Sample</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <div class="area">
    <input type="radio" name="tab_name" id="tab1" checked>
    <label class="tab_class" for="tab1">EASY</label>
    <div class="content_class">
      <div class="index_scroll_box">
      <table>
        <tr>
          <th>順位</th><th>名前</th> <th>点数</th>
        </tr>
        <% @score1.each do |score| %>
          <tr>
            <td><%= @number %></td> <td><%= score.name %></td> <td><%= score.score %></td>
          </tr>
          <% @number += 1 %>
        <% end %>
        </table>
      </div>
    </div>
    <input type="radio" name="tab_name" id="tab2" >
    <label class="tab_class" for="tab2">NOMAL</label>
    <div class="content_class">
      <div class="index_scroll_box">
      <% @number = 1 %>
      <table>
        <tr>
          <th>順位</th><th>名前</th> <th>点数</th>
        </tr>
        <% @score2.each do |score| %>
          <tr>
            <td><%= @number %></td> <td><%= score.name %></td> <td><%= score.score %></td>
          </tr>
          <% @number += 1 %>
        <% end %>
        </table>
      </div>
    </div>
    <input type="radio" name="tab_name" id="tab3" >
    <label class="tab_class" for="tab3">HARD</label>
    <div class="content_class">
      <div class="index_scroll_box">
      <% @number = 1 %>
      <table>
        <tr>
          <th>順位</th><th>名前</th> <th>点数</th>
        </tr>
        <% @score3.each do |score| %>
          <tr>
            <td><%= @number %></td> <td><%= score.name %></td> <td><%= score.score %></td>
          </tr>
          <% @number += 1 %>
        <% end %>
        </table>
      </div>
    </div>
  </div>
</body>
</html>

app/views/scores/level_1.html.erb
<div class="scroll_box">
  <table>
    <tr>
      <th>順位</th><th>名前</th> <th>点数</th>
    </tr>
  <% @score.each do |score| %>
    <tr>
    <td><%= @number %></td> <td><%= score.name %></td> <td><%= score.score %></td>
    </tr>
    <% @number += 1 %>
  <% end %>
  </table>
</div>
<%=link_to(setting_path) do %>
  <button class="rank_btn" >設定</button>
<%end%>
<%=link_to(root_path) do %>
  <button class="rank_btn" >タイトルに戻る</button>
<%end%>

app/views/scores/level_2.html.erb
<div class="scroll_box">
  <table>
    <tr>
      <th>順位</th><th>名前</th> <th>点数</th>
    </tr>
  <% @score.each do |score| %>
    <tr>
    <td><%= @number %></td> <td><%= score.name %></td> <td><%= score.score %></td>
    </tr>
    <% @number += 1 %>
  <% end %>
  </table>
</div>
<%=link_to(setting_path) do %>
  <button class="rank_btn" >設定</button>
<%end%>
<%=link_to(root_path) do %>
  <button class="rank_btn" >タイトルに戻る</button>
<%end%>

app/views/scores/level_3.html.erb
<div class="scroll_box">
  <table>
    <tr>
      <th>順位</th><th>名前</th> <th>点数</th>
    </tr>
  <% @score.each do |score| %>
    <tr>
    <td><%= @number %></td> <td><%= score.name %></td> <td><%= score.score %></td>
    </tr>
    <% @number += 1 %>
  <% end %>
  </table>
</div>
<%=link_to(setting_path) do %>
  <button class="rank_btn" >設定</button>
<%end%>
<%=link_to(root_path) do %>
  <button class="rank_btn" >タイトルに戻る</button>
<%end%>

app/views/scores/new.html.erb
<h1>Score#new</h1>
<p>Find me in app/views/scores/new.html.erb</p>